[package]
name = "jwt"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { workspace = true }
thiserror = { workspace = true }
serde = "1.0.219"
serde_json = "1.0.140"
jsonwebtoken = { version = "10.1.0", features = ["rust_crypto"] }
chrono = "0.4.40"
tracing-test = "0.2.5"
